gravity = 30
throw_speed = 15
throw_angle = 10
item_scale = 0.5
item_hold_scale = 0.7
hand_radius = 0.5
item_max_w = 5
throw_target_height = 10
ui_fov = 10
fov = 90
earth_radius = 10
sky_color = "#aaf"
ride_speed = 0.3
camera_height = 1
camera_rot = 50
road_width = 1.5
mailbox_size = 0.5
distance_between_mailboxes = 40
double_mailbox_probability = 0.1
throw_time = 0.5
item_throw_max_w = 20
item_throw_scale = 0.3
throw_height = 0.5
mailbox_colors = [
    "white",
    "#f77",
    "#7f7",
    "#77f",
    "#ff7",
    "#f7f",
    "#7ff",
    "#777",
]
juggling_score_multiplier = 100
deliver_score = 1000
spawn_distance = 0
despawn_distance = 10
hand_rotation = 20
throw_animation_time = 0.2
throw_hand_distance = 0.05
error_animation_time = 0.2
error_animation_freq = 50
error_animation_distance = 0.2

# TODO config screen
start_time = 30
time_scale = 0.5
lives = 3
