gravity = 10
throw_speed = 10
throw_angle = 10
item_scale = 0.5
item_hold_scale = 0.7
hand_radius = 0.5
item_max_w = 5
throw_target_height = 10
ui_fov = 10
fov = 90
earth_radius = 10
sky_color = "#aaf"
ride_speed = 0.1
camera_height = 1
camera_rot = 50
road_width = 1
mailbox_size = 0.5
distance_between_mailboxes = 10
throw_time = 0.5
item_throw_max_w = 20
item_throw_scale = 0.3
throw_height = 0.5
